backend:
  name: github
  repo: d-sanderson/verge
  branch: trunk
media_folder: static/assets
public_folder: /assets

collections:
  - name: albums
    label: Albums
    folder: albums
    create: true
    identifier_field: album_name
    fields:
      - { name: album_name, label: Album Name }
      - { name: artist_name, label: Aertist Name }
      - { name: album_cover_img, label: Splash Body, widget: image }
      - { name: album_sample, label: Album Sample, widget: file }
